config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/accounts')

  put '/accounts/batch', to: 'accounts#batch_update'
  post '/accounts/batch', to: 'accounts#batch_create'
  get '/accounts/batch/new', to: 'accounts#batch_new'
  get '/accounts/batch/edit', to: 'accounts#batch_edit'

  put '/transactions/batch', to: 'transactions#batch_update'
  post '/transactions/batch', to: 'transactions#batch_create'
  get '/transactions/batch/new', to: 'transactions#batch_new'
  get '/transactions/batch/edit', to: 'transactions#batch_edit'

  put '/assets/batch', to: 'assets#batch_update'
  post '/assets/batch', to: 'assets#batch_create'
  get '/assets/batch/new', to: 'assets#batch_new'
  get '/assets/batch/edit', to: 'assets#batch_edit'

  resources :accounts
  resources :transactions
  resources :assets

  namespace :reports do
    get :allocation, to: 'allocation#show'
    get :price, to: 'price#show'
    get :value, to: 'value#show'
    get :performance, to: 'performance#show'
    get :returns, to: 'returns#show'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SuperPortfolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,900" rel="stylesheet">
  </head>

  <body>
    <nav class='navbar navbar-default navbar-fixed-top'>
      <div class='container-fluid'>
        <div class='navbar-header'>
          <a class="navbar-brand" href="#">
            <div>
              <span class='normal glyphicon glyphicon-equalizer'></span>
              super<span class='navbar-brand-bold'>portfolio</span>
            </div>
            <span class='label label-danger'>beta!</span>
          </a>
        </div>
      </div>
    </nav>

    <main>
      <div class='container-fluid'>
        <%= yield %>
      </div>
    </main>

    <aside>
      <nav class='menu menu-default'>
        <ul class='nav nav-pills nav-stacked menu-nav'>
          <%= menu_item('Accounts', accounts_path) %>
          <%= menu_item('Assets', assets_path) %>
          <%= menu_item('Transactions', transactions_path) %>
          <%= menu_dropdown('Reports', '/reports') do %>
            <ul class='nav nav-pills nav-stacked menu-dropdown-list'>
              <%= menu_item('Allocation', reports_allocation_path) %>
              <%= menu_item('Price', reports_price_path) %>
              <%= menu_item('Value', reports_value_path) %>
              <%= menu_item('Performance', reports_performance_path) %>
              <%= menu_item('Returns', reports_returns_path) %>
            </ul>
          <% end %>
        </ul>
      </nav>
    </aside>
  </body>
</html>